# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 14:20
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180318_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=jsonfield.fields.JSONField(),
        ),
    ]
